### ISSUE TITLE
Complex type field change observer

### ISSUE THREAD

**Issue by foreleven** [mjolnirjs/stated-bean#10]
There are currently two ways to listen for changes in complex data types.

* vue: Array hijack, Dep watch.
* mobx: add a new decorator on the method in stated bean. 
   
for example:
```ts
@StatedBean()
class Sample {
    @Stated()
    public list: string[] = [];

    @Effect()
    add = () => {
         this.list.push('a');
    }
    
}
```

**Comment by leohxj** [comment]
mobx + 1

**Comment by JounQin** [comment]
No magic reactive, more declarative in React.

**Comment by foreleven** [comment]
I think reassignment is the most simple way.

```js
this.array = [...this.array, item];
this.obj = {
   ...this.obj,
   name: 'test'
};
```

**Comment by JounQin** [comment]
More `React` way.😂
