### ISSUE TITLE
[RFC] useStatedBean with scope

### ISSUE THREAD

**Issue by foreleven** [mjolnirjs/stated-bean#27]
`useStatedBean(Model)` will find the model from the provider in the context, and will report an error if it does not exist. This feels unreasonable. It should be possible to temporarily create an instance of the `Model` whose lifecycle is consistent with the current component.

`useStatedBean(Model, Scope?)` 

proposed scopes:
- `Default`: if existed in `Context` then `Request`
- `Request`: temporarily create an instance whose lifecycle is consistent with the current component.
- `Context`: find from the provider in the context

**Comment by JounQin** [comment]
`temporarily create an instance`

How will you implement it, If the Model has other depencies?

It it doesn't have any dependence, why not just `useState(() => new Model())`

**Comment by foreleven** [comment]
> So I think we should still resolve Model via DI, but we need find a way to register Models dynamicly.

totally agree.

Currently,  `StatedBeanContainer` caches the instance retrieved from the BeanFactory, and then `useStatedBean` got the cached object from the container in the context.

Now, how to create the container in `useStatedBean` when with the `Request` scope?

temporarily  store the container with `useState`
```ts
interface UseStatedBeanOptions {
  dependentFields?: Array<string | symbol>;
 scope?: Scope
}

export function useStatedBean<T extends ClassType>(
  type: T,
  options?: UseStatedBeanOptions,
): InstanceType<T> {
  useState(() => {
       let container
       if (options.scope === Scope.Request) {
           container = new StatedBeanContainer(...);
       } else {
          // get container from context
       }
       return container;
   });
   ...  
}
```
